### ISSUE TITLE
Inverted timeseries cycle plotting does not work properly

### ISSUE THREAD

**Issue by GES-mpalermo** [GES-compchem/GES-echem-suite#14]
If the sampling rate of the cellcycling is based on constant mV and not seconds, then the timeserie will have different time deltas between each element. This generate an artifact when reversing the series, for which the elementwise delta is not conserved, and therefore the plot is not shown properly.

Fix this issue in order to get the correct inverted plot.

**Comment by GES-compchem** [comment]
Fixed in #15
