### ISSUE TITLE
Allow user to hide cycles in CellCycling instances

### ISSUE THREAD

**Issue by GES-mpalermo** [GES-compchem/GES-echem-suite#21]
Allow the user to manually hide cycles from CellCycling instances. Cycles should not be deleted so that data can be shown again if necessary?

Example:
``` python
...
cycles.indexes # to be implemented
# returns [0, 1, 2, 3, 4, 5]
cycles.coulombic_efficiencies
# returns [99, 96, 57, 98, 94, 33]

cycles.mask([2, 4, 5]) # use list of cycles indexes

cycles.indexes
# returns [0, 1, 3]
cycles.coulombic_efficiencies
# returns [99, 96, 98]

cycles.unmask([2]) # unmask selected cycles
cycles.indexes
# returns [0, 1, 2, 3]
cycles.coulombic_efficiencies
# returns [99, 96, 57, 98]

cycles.unmask() # unmask all cycles
cycles.indexes
# returns [0, 1, 2, 3, 4, 5]
cycles.coulombic_efficiencies
# returns [99, 96, 57, 98, 94, 33]

```
It could be done by modifiying the `__iter__` method to check on a list of hidden cycles, and editing the properties to cycle on `self` rather than on the `self._cycles` instance attribute. 

The `capacity_retention` property should be modified to calculate the retentions on the spot, e.g.:

``` python
cycles.capacities
# returns [100, 50, 50, 50]
cycles.capacity_retention
# returns [100, 50, 50, 50]

cycles.reference = 1
cycles.capacity_retention
# returns [200, 100, 100 ,100]
```
We can then remove the function `calculate_capacity_retention`. @GES-lbabetto what do you think?

We should implement the capacity retentions calculation via numpy instead of cyclying in a python for loop :)

**Comment by GES-lbabetto** [comment]
Cycles masking/unmasking feature added in pull request #23

**Comment by GES-lbabetto** [comment]
On-the-spot retention calculations feature added in pull request #23
