### ISSUE TITLE
Error in the computation of the capacity fade?

### ISSUE THREAD

**Issue by GES-ppravatto** [GES-compchem/GES-echem-suite#49]
The `capacity_fade` property, pointing to the `_capacity_fade` inner variable assumes values not compatible with a percentage. A better explanation of the parameter definition or a bug-fix is required.

 If the capacity fade is intended as the linear capacity loss associated to each charge/discharge cycle the value computed do not appear to match physical meaning. The source of error can be located at [this line](https://github.com/GES-compchem/GES-echem-suite/blob/main/echemsuite/cellcycling/read_input.py#L122). The `_retention_fit_parameters.slope` already derives from the fitting of percentage `capacity_retention` values and, as such, the multiplication by the factor `100` should not be required.

**Comment by GES-lbabetto** [comment]
@GES-mpalermo ricordo che di questa cosa ne avevamo già parlato e ci eravamo già "scontrati" con gli sperimentali per la definizione di questa capacity fade. Chiedo a Elisa/Eneko delucidazioni a riguardo e nel caso pusho un fix! :D
