### ISSUE TITLE
Cycle hiding on missing charge halfcycle even without clean, feature or bug?

### ISSUE THREAD

**Issue by GES-ppravatto** [GES-compchem/GES-echem-suite#50]
[Line 750 of the `cellcycling.read_input` module](https://github.com/GES-compchem/GES-echem-suite/blob/main/echemsuite/cellcycling/read_input.py#L750) always triggers the hiding of the whole cycle if the charge halfcycle is missing. This happens even if the `clean` option is set to `False`. 

If this is wanted close this issue, else a bug-fix is needed to set the correct ordering of the logic operator chain. 

Suggested fix:
```
elif (not cycle.charge or not cycle.discharge) and clean:
```

**Comment by GES-lbabetto** [comment]
Intended behaviour is as per the suggested fix, cycles should be automatically hidden only if the `clean` flag is active.

Suggested fix approved!

**Comment by GES-ppravatto** [comment]
I will implemented the fix on the `FileManager` class development branch that will substitute the body of the `build_DTA_cycles`. The bug will be resolved on the next pull request.
